apiVersion: batch/v1

kind: CronJob

metadata:
  name: sre # Follow naming convention - capital not accepted

spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: sre
            image: busybox
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - -c
            - date; echo thank you fro using cronjob

          restartPolicy: OnFailure