---

apiVersion: v1
kind: Service
# Metadata for name
metadata:

  name: nginx-svc
  namespace: default

spec:
  ports:
  - nodePort: 30442
    port: 80
    protocol: TCP
    targetPort: 80

  
# Lets define the selector and label to connect to nginx deployment
  selector:
    app: nginx # This label connects this service to deployment

  # Creating LoadBalancer type of deployment
  type: LoadBalancer
