# K8 works w API versions to declare the resources
# We have to declare the apiVersion ans the kind of service/component

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment # Naming the deployment

spec:
  selector:
    matchLabels:
      app: nginx # Look for this label to mtch w K8 service

  # Let's creatw a replica set of this with 2 instances/pods
  replicas: 2

  # Template to use its label for K8 service to launch in the browser
  template:
    metadata:
      labels:
        app: nginx # This label connects to the service

    # Let's define the container spec
    spec:
      containers:
        - name: nginx
          image: akunduj/sre_node_app:v1
          ports:
          - containerPort: 80
