---

apiVersion: v1
kind: Service
# Metadata for name
metadata:

  name: nginx-deployment
  namespace: default

spec:
  ports:
  - nodePort: 30442
    port: 80
    protocol: TCP
    targetPort: 80

  
# Lets define the selector and label
  selector:
    app: nginx # This label connects this service to deployment

  # Creatikng LoadBalancer type of deployment
  type: LoadBalancer
