# Create a diagram for node deployment and service
# Use the example of Nginx deployment and service
# Nodeapp deployment to have 3 pods min -
# Service within the same cluster and namespace to connect to node deploy
# type LoadBalancer
# end goal is to see our node app running port loaclhost:3000
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: node
spec:
  selector:
    matchLabels:
      app: node
  replicas: 1
  template:
    metadata:
      labels:
        app: node
    spec:
      containers:
        - name: node
          image: zeeshanj/sre_node_app:latest
          ports:
            - containerPort: 3000
          env:
            - name: DB_HOST
              value: mongodb://mongo:27017/posts
        