# Create node_hpa.yml
# Create an AutoScaling Group for our node app
---


apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler #(HPA)

metadata:
  name: sparta-node-app-deploy
  namespace: default

spec:
  maxReplicas: 9 #(Max no. of instances/pods)
  minReplicas: 3
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: node
  targetCPUUtilizationPercentage: 50 # 50% of CPU usage